---
title: "IS2000 Assignment / Getting to Know R"
author: "Balaji, Vinayajitesh"
date: "Spring 2024"
output:
  html_document:
    df_print: paged
---

## Question 2
```{r Q2_LoadCSV, echo=FALSE}
  # Define the URL where the dataset is located
  url <- "https://s3.us-east-2.amazonaws.com/artificium.us/datasets/FlightsWithAirlines.csv"
  # Read the CSV file from the URL into a data frame
  df.flights <- read.csv(url, stringsAsFactors = FALSE)
```

## Question 3
```{r Q3_Calculations, echo=FALSE}
  # Count the number of rows in the data frame
  num_observations <- nrow(df.flights)
  # Count the number of columns in the data frame
  num_columns <- ncol(df.flights)
  # Calculate the average mean departure delay across all flights
  avg_departure_delay <- mean(df.flights$dep_delay)
  # Count the number of flights with a departure delay greater than 60 minutes
  num_long_delays <- sum(df.flights$dep_delay > 60)
```

The dataset contains `r num_observations` observations (rows) and `r num_columns` columns. Each row is information about a flight, including departure and departure delay information. The average mean departure delay is `r round(avg_departure_delay, 0)` minutes. A total of `r num_long_delays` flights experienced a delay of more than an hour.

## Question 4
```{r Q4_AddColumn, echo=FALSE}
  # Calculate the actual departure hour and minute
  df.flights$actual_dep_hr <- df.flights$dep_hr + floor(df.flights$dep_delay / 60)
  df.flights$actual_dep_min <- df.flights$dep_min + (df.flights$dep_delay %% 60)
  
  # Adjust for cases where minutes go over 59
  df.flights$actual_dep_hr <- df.flights$actual_dep_hr + floor(df.flights$actual_dep_min / 60)
  df.flights$actual_dep_min <- df.flights$actual_dep_min %% 60
  
  # Adjust for cases where hours go over 23
  df.flights$actual_dep_hr <- df.flights$actual_dep_hr %% 24
  
  # Define night as after 7pm or before 5am
  df.flights$isNight <- ifelse(df.flights$actual_dep_hr >= 19 | df.flights$actual_dep_hr < 5, TRUE, FALSE)
  
  # Print the data frame to check the new column
  head(df.flights)
```