---
title: "IS 2000 Assignment / Getting to Know R"
author: Steven Boehm
date: Spring 2024
output : html_document
---

## Question 2

```{r Q2_LoadCSV}

 # Loading in csv file into a dataframe
 df.flights <- read.csv(file = "https://s3.us-east-2.amazonaws.com/artificium.us/datasets/FlightsWithAirlines.csv", header = T, stringsAsFactors = FALSE)
 
 # Extracting row and column counts
 observations <- nrow(df.flights)
 columns <- length(df.flights)
 
 # Extracting the delay column and calculating the mean
 delays <- df.flights$dep_delay
 mean_delay <- round(sum(delays) / nrow(delays))
 
 # Filtering for >60 minute delays and returning the count
 hour_delay <- which(df.flights$"dep_delay">60)
 num_hour_delay <- length(hour_delay)
 
```

The dataset contained `r observations` observations, and `r columns` columns. Each row is information about a flight, including departure and departure delay information. The average mean departure delay is `r mean_delay` minutes.  A total of `r num_hour_delay` flights experienced a delay of more than an hour.


## Question 3 

``` {r Q3_ifNight}

 # Setting constants representing the edges of our time limit
 max_time <- 19 * 60
 min_time <- 7 * 60

 # Creating a column by converting all time to minutes, adding in delays, and determining if it is inside the night or day range
 df.flights$isNight<- ifelse(((df.flights$dep_hr * 60) + df.flights$dep_min + df.flights$dep_delay) < min_time | ((df.flights$dep_hr * 60) + df.flights$dep_min + df.flights$dep_delay) > max_time, "T", "F")
 
 print(df.flights)
```
